version: '3'
services:
  server:
    image: analizer_api
    build: .
    command: ["server"]
    environment:
      - DATABASE_URI=postgresql://postgres-db:5432/analizer?user=postgres&password=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASS=${ADMIN_PASS}
    volumes:
      - ./analizer_api:/code/analizer_api
    depends_on:
      - postgres-db
    ports:
      - 5000:5000


  postgres-db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-local
    volumes:
      - ./client:/code/client
      - node_modules:/code/client/node_modules
    ports:
      - 80:3000
    depends_on:
      - server

volumes:
  node_modules:
  db-data:
    driver: local
