version: '3'
services:

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_OPTIONS=--max_old_space_size=8192 # wywalić jak Vue będzie marudzić
    volumes:
      - ./client:/code/client
      - node_modules:/code/client/node_modules
    ports:
      - 80:80

volumes:
  node_modules: