version: '3'
services:
  backend:
    image: backend
    build: .
    command: ["server"]
    environment:
      - DATABASE_URI=postgresql://${DB_HOST}:5432/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASS=${ADMIN_PASS}
    volumes:
      - ./backend:/code/backend
    depends_on:
      - postgres-db
    ports:
      - 5000:5000

  postgres-db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

#  frontend:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    environment:
#      - NODE_OPTIONS=--max_old_space_size=8192 # wywalić jak Vue będzie marudzić
#    volumes:
#      - ./client:/code/client
#      - node_modules:/code/client/node_modules
#    ports:
#      - 80:80
#    depends_on:
#      - backend

volumes:
  node_modules:
  db-data:
    driver: local